{
 "title": "Monitorización Meteorológica v2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "Ciudad",
    "query": "label_values(http_server_duration_sum, city)"
   }
  ]
 },
 "panels": [
  {
   "title": "Desglose de Tiempo por Paso (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_sum{city=\"$city\"}[1m]) \r\n/ \r\nrate(http_server_duration_count{city=\"$city\"}[1m])",
     "legendFormat": "{{step}}{{endpoint}}"
    }
   ]
  },
  {
   "title": "Estado de Alerta (>1s)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_duration_sum{city=\"$city\", endpoint=~\".+\"}[1m]) \r\n/ \r\nrate(http_server_duration_count{city=\"$city\", endpoint=~\".+\"}[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Peticiones Totales (Ciudad Seleccionada)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_count{city=\"$city\", endpoint=\"fetchAndSaveWeather\"})",
     "legendFormat": "Peticiones en $city"
    }
   ]
  }
 ]
}